/* ============================================================
   قاموس الترجمة — عربي ⇄ إنجليزي
   لإضافة أو تعديل نص: أضف سطراً في dict بالشكل:
     "النص العربي بالضبط": "English text",
   أو قاعدة نمطية في patterns إذا كان النص يحتوي أرقاماً/متغيرات.
   ============================================================ */

window.ARABEKA_LANG = {

    dict: {
        /* ===== الواجهة العامة ===== */
        "أرابيكا - مجتمع التجارة الرقمية": "Arabeka - Digital Commerce Community",
        "أرابيكا🎗": "Arabeka 🎗",
        "آرابيكا": "Arabeka",
        "⚜️ ارابيكا": "⚜️ Arabeka",
        "أرابيكا": "Arabeka",
        "📌 بيتم عرض منتجاتك بس": "📌 Showing your products only",
        "تعديل البيانات": "Edit Data",
        "حفظ التغييرات": "Save Changes",
        "إلغاء": "Cancel",
        "القائمة": "List",
        "إغلاق": "Close",
        "مسح": "Clear",
        "الحقل الأول": "First field",

        /* ===== شاشة الدخول ===== */
        "مرحباً بك في مجتمع أرابيكا": "Welcome to the Arabeka Community",
        "انضم إلى مجتمعنا وابدأ التجارة الآن": "Join our community and start trading now",
        "🤖 اسأل مساعد أرابيكا": "🤖 Ask Arabeka Assistant",
        "بيع الخدمات والمنتجات": "Sell services and products",
        "تواصل آمن": "Secure communication",
        "بياناتك مشفرة": "Your data is encrypted",
        "ادفع واستلم أموالك": "Pay and receive your money",
        "بـ Pi wallet": "With Pi wallet",
        "بيع منتجاتك": "Sell your products",
        "وخدماتك بسهولة": "and services easily",
        "تفاعل مع المجتمع": "Engage with the community",
        "تصفح المتجر": "Browse Store",
        "الرجاء فتح التطبيق من متصفح Pi": "Please open the app in Pi Browser",
        "لسه بيجهز الاتصال بـ Pi، بنحاول تاني تلقائياً...": "Still preparing the Pi connection, retrying automatically...",
        "فشل التوثيق الأمني مع الخادم": "Server authentication failed",
        "انتهت صلاحية جلستك القديمة، برجاء تسجيل الدخول من جديد.": "Your old session expired, please sign in again.",
        "انتهت الجلسة، سجّل الدخول من جديد": "Session expired, please sign in again",
        "إعادة توثيق صامتة مع Pi فشلت:": "Silent Pi re-auth failed:",
        "هل تريد تسجيل الخروج؟": "Do you want to log out?",

        /* ===== التنقل والتبويبات ===== */
        "الملف الشخصي": "Profile",
        "الإعدادات": "Settings",
        "البحث والأصدقاء": "Search & Friends",
        "طلباتي": "My Orders",

        /* ===== التغذية (المنشورات) ===== */
        "💬 عام": "💬 General",
        "📖 تعليمي": "📖 Educational",
        "🙋 شخصي": "🙋 Personal",
        "💻 تكنولوجيا": "💻 Technology",
        "📊 سياسة واقتصاد": "📊 Politics & Economy",
        "✓ نشر الرأي": "✓ Post Opinion",
        "⚡️شارك رأيك": "⚡️ Share your opinion",
        "رجوع": "Back",
        "🌐 الكل": "🌐 All",
        "📌 بتعرض منشوراتك بس": "📌 Showing your posts only",
        "عرض الكل": "Show All",
        "منشوراتي": "My Posts",
        "نص المنشور...": "Post text...",
        "هل تعجبك آربيكا؟ شارك تجربتك وآراءك...": "Do you like Arabeka? Share your experience...",
        "🔗 رابط صورة (اختياري)": "🔗 Image URL (optional)",
        "أضف نصاً أو صورة": "Add text or an image",
        "حذف المنشور؟": "Delete this post?",
        "اكتب تعليقاً...": "Write a comment...",
        "إرسال": "Send",
        "تعديل": "Edit",
        "تعديل المنشور": "Edit Post",
        "حفظ التعديلات": "Save Changes",
        "تم نسخ المنشور": "Post copied",
        "المشاركة غير مدعومة على هذا المتصفح": "Sharing is not supported on this browser",
        "المشاركة مش مدعومة": "Sharing not supported",
        "مجهول": "Anonymous",
        "منشورات المستخدم": "User Posts",

        /* ===== المتجر ===== */
        "➕ أضف منتجك للسوق": "➕ Add your product to the market",
        "💡 تُخصم رسوم منصة 0.1 Pi من كل عملية بيع عند التحويل للبائع.": "💡 A 0.1 Pi platform fee is deducted from every sale when transferred to the seller.",
        "عرض للبيع": "For Sale",
        "أحدث المنتجات": "Latest Products",
        "📌 بتعرض منتجاتك بس": "📌 Showing your products only",
        "اسم المنتج": "Product name",
        "السعر (Pi)": "Price (Pi)",
        "الكمية المتاحة (اتركه فارغاً = غير محدود)": "Available quantity (leave empty = unlimited)",
        "رابط الصورة": "Image URL",
        "وصف المنتج (اختياري، حتى 250 حرف)": "Product description (optional, up to 250 chars)",
        "💻 تقني": "💻 Tech",
        "🎮 ترفيهي": "🎮 Entertainment",
        "🛠️ خدمي": "🛠️ Services",
        "🏭 صناعي": "🏭 Industrial",
        "🛒 منتج": "🛒 Product",
        "اكتب اسم المنتج": "Enter product name",
        "الكمية يجب أن تكون رقماً صحيحاً": "Quantity must be a whole number",
        "رابط الصورة غير صالح": "Invalid image URL",
        "تم عرض منتجك للبيع ✅": "Your product is now listed ✅",
        "✏️ تعديل بيانات المنتج": "✏️ Edit Product Data",
        "السعر (Pi) — أكبر من 0.1": "Price (Pi) — greater than 0.1",
        "🔗 رابط صورة المنتج (اختياري)": "🔗 Product image URL (optional)",
        "📝 وصف المنتج (اختياري، حتى 250 حرف)": "📝 Product description (optional, up to 250 chars)",
        "هل أنت متأكد من حذف هذا المنتج نهائياً؟": "Are you sure you want to permanently delete this product?",
        "نفذت": "Out",
        "شراء": "Buy",
        "تفاصيل": "Details",
        "نفذت الكمية": "Out of stock",
        "متوفر": "In stock",
        "غير محدود": "Unlimited",
        "هذا منتجك": "This is your product",
        "لا توجد منتجات بعد": "No products yet",
        "السعر:": "Price:",
        "التصنيف:": "Category:",
        "البائع:": "Seller:",
        "المتاح:": "Available:",
        "الوصف:": "Description:",
        "إتمام الشراء": "Complete Purchase",
        "المنتج غير متاح": "Product unavailable",
        "نظام Pi غير متاح هنا": "Pi is not available here",
        "مينفعش تشتري منتجك بنفسك": "You can't buy your own product",
        "جاري الاتصال بشبكة Pi، يرجى المحاولة بعد ثانية...": "Connecting to the Pi network, please try again in a moment...",
        "رفض السيرفر الطلب": "The server rejected the request",
        "تم الدفع بنجاح! الفلوس محجوزة لحد ما تأكد استلامك من صفحة \"طلباتي\".": "Payment successful! Funds are held until you confirm receipt from the \"My Orders\" page.",
        "تم الدفع لكن تعذر تأكيده الآن، سيُستكمل تلقائياً عند فتح التطبيق.": "Payment made but couldn't be confirmed now; it will complete automatically when you open the app.",
        "خطأ في الشبكة": "Network error",

        /* ===== الطلبات ===== */
        "🛍️ مشترياتي": "🛍️ My Purchases",
        "💰 مبيعاتي": "💰 My Sales",
        "🔄 جارٍ تأكيد الدفع": "🔄 Confirming payment",
        "⏳ محجوز - في انتظار التأكيد": "⏳ Held - awaiting confirmation",
        "🔄 جارٍ التحويل للبائع": "🔄 Transferring to seller",
        "✅ تم التحويل للبائع": "✅ Transferred to seller",
        "⚠️ نزاع مفتوح": "⚠️ Dispute open",
        "↩️ تم الاسترداد للمشتري": "↩️ Refunded to buyer",
        "البائع": "Seller",
        "المشتري": "Buyer",
        "منتج": "Product",
        "⏳ جارٍ التحويل...": "⏳ Transferring...",
        "فشل التحرير": "Release failed",
        "✅ تأكيد الاستلام": "✅ Confirm Receipt",
        "تم تأكيد الاستلام وتحويل الفلوس للبائع ✅": "Receipt confirmed and funds transferred to seller ✅",
        "اكتب سبب فتح النزاع بإيجاز:": "Briefly write the reason for opening a dispute:",
        "تم فتح النزاع، هيتم مراجعته من فريق الدعم.": "Dispute opened; our support team will review it.",
        "🛍️ المشتريات والمبيعات": "🛍️ Purchases & Sales",

        /* ===== الملف الشخصي ===== */
        "نبذه 🫆": "Bio 🫆",
        "تعديل نبذه": "Edit Bio",
        "تعديل النبذة": "Edit Bio",
        "متابعة": "Follow",
        "المتابعين": "Followers",
        "المنشورات": "Posts",
        "عروض البيع": "Listings",
        "المهام 🎯": "Tasks 🎯",
        "أكمل نبذتك الشخصية": "Complete your bio",
        "انشر أول منشور": "Publish your first post",
        "تابع أول شخص": "Follow someone",
        "🥇 عضو أساسي": "🥇 Basic Member",
        "🥈 عضو مميز": "🥈 Premium Member",
        "🥉 عضو نشط": "🥉 Active Member",
        "تاريخ الانضمام: 2024": "Join date: 2024",
        "المحفظة: ": "Wallet: ",
        "المحفظة:": "Wallet:",
        "غير مرتبطة": "Not linked",
        "👤 إعدادات الحساب": "👤 Account Settings",
        "تغيير صورة الحساب": "Change Profile Picture",
        "مُعرف Pi": "Pi ID",
        "📄 السياسات والقوانين": "📄 Policies & Terms",
        "سياسة الخصوصية": "Privacy Policy",
        "الشروط والأحكام": "Terms & Conditions",
        "هنستناك ياحبيبنا 🫡": "We'll be waiting for you 🫡",
        "🚪 تسجيل الخروج": "🚪 Log Out",
        "الحقل مطلوب": "This field is required",
        "رابط صورة الحساب": "Profile picture URL",
        "الرابط غير صالح — لازم يبدأ بـ http:// أو https://": "Invalid URL — must start with http:// or https://",

        /* ===== الأصدقاء والمتابعة ===== */
        "أصدقاء": "Friends",
        "🤝 إضافة صديق": "🤝 Add Friend",
        "✅ أصدقاء": "✅ Friends",
        "⏳ تم إرسال الطلب": "⏳ Request sent",
        "➕ متابعة": "➕ Follow",
        "✓ متابَع": "✓ Following",
        "قبول": "Accept",
        "رفض": "Decline",
        "📨 ادعُ أصدقاءك لأرابيكا": "📨 Invite your friends to Arabeka",
        "طلبات الصداقة الواردة": "Incoming Friend Requests",
        "لا توجد طلبات حالياً": "No requests currently",
        "انضم لي على أرابيكا 🎗 — مجتمع تجارة وتواصل عبر شبكة Pi Network": "Join me on Arabeka 🎗 — a trading & social community on the Pi Network",
        "تم نسخ رابط الدعوة!": "Invite link copied!",
        "تعذر النسخ": "Copy failed",
        "تعذر تحميل القائمة": "Couldn't load the list",
        "تعذر البحث حالياً": "Search unavailable right now",
        "ابحث باسم المستخدم...": "Search by username...",
        "الحسابات اللي بيتابعها": "Accounts they follow",
        "الحسابات اللي بتتابعها": "Accounts you follow",
        "لسه بيجهز الاتصال الآمن، حاول تاني بعد ثانية": "Secure connection is still preparing, try again in a moment",
        "✔️ قبول طلب الصداقة": "✔️ Accept friend request",

        /* ===== الدعم ===== */
        "الدعم": "Support",
        "مساعد أرابيكا": "Arabeka Assistant",
        "الإعداد قيد التطوير 🤌": "This feature is coming soon 🤌",

        /* ===== إضافات 2026-09-10: نصوص ناقصة + احتياط للنسخة المشوّهة ===== */
        "✏️ تعديل": "✏️ Edit",
        "🔗 مشاركة": "🔗 Share",
        "لا توجد مشتريات بعد": "No purchases yet",
        "لا توجد مبيعات بعد": "No sales yet",
        "لا": "No",
        "تسجيل الدخول باستخدام Pi": "Sign in with Pi",
        "محفظة باي": "Pi Wallet",
        "الأصدقاء": "Friends",
        "🤝 أضف صديقًا": "🤝 Add Friend",
        "طلبات الصداقة ترسل": "Incoming Friend Requests",
        "لا توجد طلبات متاحة": "No requests currently",
        "المتابعون": "Followers",
        "عروض بيع": "Listings",
        /* احتياط: نصوص النسخة المشوّهة (يصحّحها i18n.js تلقائياً أيضاً) */
        "الإله": "Settings",
        "تعديل نبهم": "Edit Bio",
        "نبزة 🫆": "Bio 🫆",
        "الزر": "Cancel",
        "حفظ الأشياء": "Save Changes",
        "حفظ المنتج": "Save Product",
        "الحق الأول": "First field",
        "عرض البيع": "For Sale",
        "💻 تمرير": "💻 Tech",
        "🛠️ خدمة": "🛠️ Services",
        "🛠️ خدماتي": "🛠️ Services",
        "🏭 صناعية": "🏭 Industrial",
        "📊 سيارة واقتصاد": "📊 Politics & Economy",
        "✓ نشر": "✓ Post Opinion",
        "تعرض منشوراتك بس": "📌 Showing your posts only",
        "تعرض منتجاتك بس": "📌 Showing your products only",
        "💡 تُخصم منصة رسم 0.1 Pi من كل عملية بيع عند تحويل للبائع.": "💡 A 0.1 Pi platform fee is deducted from every sale when transferred to the seller.",
        "🛍️ المشترين والمبيعات": "🛍️ Purchases & Sales",
        "📄 المستهلكين والقوانين": "📄 Policies & Terms",
        "⚜️ ara man": "⚜️ Arabeka",
        "⚜️ ara ظرف": "⚜️ Arabeka",
        /* ===== إضافات جولة 2026-09-10 (هـ): نصوص اللقطات الأخيرة + المحفظة ===== */
        "✍️ إدخال يدوي": "✍️ Enter manually",
        "أدخل عنوان محفظتك (56 حرفاً يبدأ بحرف G):": "Enter your wallet address (56 characters starting with G):",
        "العنوان غير صحيح — لازم يبدأ بحرف G ويكون 56 حرفاً": "Invalid address — it must start with G and be 56 characters",
        "✅ تم حفظ عنوان المحفظة": "✅ Wallet address saved",
        "لازم تسجل الدخول الأول": "You need to sign in first",
        "لم يُمنح إذن عنوان المحفظة (الأذونات: لا شيء) — استخدم «إدخال يدوي»": "Wallet address permission not granted (scopes: none) — use the manual entry option",
        "التبديل للعربية": "Switch to Arabic",
        "التبديل للإنجليزية": "Switch to English",
        "🤖 مساعد أرابيكا": "🤖 Arabeka Assistant",
        "💰 المبيعات": "💰 Sales",
        "💻 تكنولوجي": "💻 Technology",
        "معرف Pi": "Pi Username",
        "كارت آرابيكا": "Arabeka Card",
        "كارت آرا شين": "Arabeka Card",
        "🔗 رابط الصورة (اختياري)": "🔗 Image URL (optional)",
        "السعر (Pi) - أكبر من 0.1": "Price (Pi) - greater than 0.1",
        "الكمية المتاحة (اتركه كاملاً = غير محدود)": "Available quantity (leave empty = unlimited)",
        "تاريخ الانضمام": "Join date",
        "لا توجد منشورات بعد": "No posts yet",
        "لا توجد منشورات": "No posts",
        "لا يوجد نتائج": "No results",
        "لا يوجد بيانات بعد": "No data yet",
        "عرض الملف": "View Profile",
        "متوفر:": "Available:",
        "حذف": "Delete",
        "⚠️ فتح نزاع": "⚠️ Open Dispute",
        "السعر يجب أن يكون أكبر من": "Price must be greater than",
        "Pi (رسوم المنصة)": "Pi (platform fee)",
        "🔗 ربط المحفظة": "🔗 Link wallet",
        "⏳ جارٍ طلب إذن المحفظة...": "⏳ Requesting wallet permission...",
        "✅ تم ربط المحفظة بنجاح": "✅ Wallet linked successfully",
        "لم يمنح Pi الإذن بعنوان المحفظة — جرّب مرة أخرى": "Pi didn't grant wallet address permission — try again",
    },

    /* ===== قواعد للنصوص المتغيرة (تحتوي أرقاماً أو محتوى ديناميكي) ===== */
    patterns: [
        /* المهام (نص مركب: ⬜ المهمة (+نقاط)) */
        { r: /^([⬜✅]) أكمل نبذتك الشخصية \(\+(\d+)\)$/, en: "$1 Complete your bio (+$2)" },
        { r: /^([⬜✅]) انشر أول منشور \(\+(\d+)\)$/, en: "$1 Publish your first post (+$2)" },
        { r: /^([⬜✅]) تابع أول شخص \(\+(\d+)\)$/, en: "$1 Follow someone (+$2)" },
        /* شارة الولاء (🥈 عضو مميز · عدد نقطة) */
        { r: /^🥇 عضو أساسي · (\d+) نقطة$/, en: "🥇 Basic Member · $1 points" },
        { r: /^🥈 عضو مميز · (\d+) نقطة$/, en: "🥈 Premium Member · $1 points" },
        { r: /^🥉 عضو نشط · (\d+) نقطة$/, en: "🥉 Active Member · $1 points" },
        /* الطلبات */
        { r: /^البائع: (.+)$/, en: "Seller: $1" },
        { r: /^المشتري: (.+)$/, en: "Buyer: $1" },
        { r: /^تعذر تحميل المشتريات \((.+)\)$/, en: "Couldn't load purchases ($1)" },
        { r: /^تعذر تحميل المبيعات \((.+)\)$/, en: "Couldn't load sales ($1)" },
        /* بادئات رسائل الأخطاء (بادئة ثابتة + نص متغير) */
        { r: /^خطأ في المتابعة: ?(.*)$/, en: "Follow error: $1" },
        { r: /^خطأ بالحفظ: ?(.*)$/, en: "Save error: $1" },
        { r: /^خطأ بحفظ الصورة: ?(.*)$/, en: "Avatar save error: $1" },
        { r: /^خطأ النشر: ?(.*)$/, en: "Post error: $1" },
        { r: /^خطأ في التعديل: ?(.*)$/, en: "Edit error: $1" },
        { r: /^تعذر الحذف: ?(.*)$/, en: "Delete failed: $1" },
        { r: /^خطأ في الإعجاب: ?(.*)$/, en: "Like error: $1" },
        { r: /^تعذر إضافة التعليق: ?(.*)$/, en: "Couldn't add comment: $1" },
        { r: /^تعذر إضافة المنتج: ?(.*)$/, en: "Couldn't add product: $1" },
        { r: /^خطأ في تعديل المنتج: ?(.*)$/, en: "Product edit error: $1" },
        { r: /^خطأ في الدفع: ?(.*)$/, en: "Payment error: $1" },
        { r: /^خطأ السيرفر: ?(.*)$/, en: "Server error: $1" },
        { r: /^خطأ تسجيل الدخول: ?(.*)$/, en: "Login error: $1" },
        { r: /^تعذر إلغاء الطلب: ?(.*)$/, en: "Couldn't cancel the request: $1" },
        { r: /^تعذر قبول الطلب: ?(.*)$/, en: "Couldn't accept the request: $1" },
        { r: /^تعذر رفض الطلب: ?(.*)$/, en: "Couldn't decline the request: $1" },
        { r: /^تعذر إرسال طلب الصداقة: ?(.*)$/, en: "Couldn't send friend request: $1" },
        { r: /^تعذر فتح النزاع: ?(.*)$/, en: "Couldn't open dispute: $1" },
        { r: /^تعذر إتمام العملية: ?(.*)$/, en: "Couldn't complete the operation: $1" },
        { r: /^لم تتم الموافقة على الدفع: ?(.*)$/, en: "Payment was not approved: $1" },
        { r: /^فشل الاتصال للموافقة: ?(.*)$/, en: "Approval connection failed: $1" },
        { r: /^إلغاء: ?(.*)$/, en: "Cancelled: $1" },
        { r: /^إعادة توثيق صامتة مع Pi فشلت: ?(.*)$/, en: "Silent Pi re-auth failed: $1" },
        { r: /^خطأ: ?(.*)$/, en: "Error: $1" },
        { r: /^متوفر: (\d+)$/, en: "In stock: $1" },
        { r: /^(\d+) نقطة$/, en: "$1 points" },
        { r: /^نقطة$/, en: "pts" },
        { r: /^💬 تعليقات \((\d+)\)$/, en: "💬 Comments ($1)" },
        { r: /^بواسطة: ?(.*)$/, en: "By: $1" },
        { r: /^زائر تلجرام #(\d+)$/, en: "Telegram guest #$1" },
        { r: /^زائر تلجرام #/, en: "Telegram guest #" },
        { r: /^\(معدّل\)$/, en: "(edited)" },
        { r: /^السعر يجب أن يكون أكبر من (.+?) Pi \(رسوم المنصة\)$/, en: "Price must be greater than $1 Pi (platform fee)" },
        { r: /^السعر يجب أن يكون أكبر من (.+)$/, en: "Price must be greater than $1" },
        { r: /^📌 بيتم عرض منتجات (.+) فقط$/, en: "📌 Showing products of $1 only" },
        { r: /^📌 بيتم عرض منتجاتك فقط$/, en: "📌 Showing your products only" },
        { r: /^صافي بعد رسوم المنصة \(([\d.]+)\):$/, en: "Net after platform fee ($1):" },
        { r: /^تأكيد إنك استلمت المنتج\/الخدمة؟[\s\S]*$/, en: "Confirm you received the product/service? Funds will be transferred to the seller (after platform fee deduction). This action is final." },
        { r: /^رد غير متوقع من الخادم \(([\d]+)\)$/, en: "Unexpected server response ($1)" },
        { r: /^رد غير متوقع من الخادم/, en: "Unexpected server response" }
        ,
        /* جولة (هـ): نصوص ناقصة من لقطات 2026-09-10 */
        { r: /^لم يُمنح إذن عنوان المحفظة \(الأذونات: (.+)\) — استخدم «إدخال يدوي»$/, en: 'Wallet address permission not granted (scopes: $1) — use the manual entry option' },
        { r: /^تم الدفع لكن تعذر تأكيده الآن، سيُستكمل تلقائياً عند فتح التطبيق\. ?(.*)$/, en: "Payment was made but couldn't be confirmed now; it will complete automatically when you open the app. $1" },
        { r: /^متوفر: (.+)$/, en: "Available: $1" }, /* متوفر: الرقم */
        { r: /^تعذر تحميل المنشورات \((.+)\)$/, en: "Couldn't load posts ($1)" }, /* تعذر تحميل المنشورات */
        { r: /^تعذر تحميل الطلبات \((.+)\)$/, en: "Couldn't load requests ($1)" }, /* تعذر تحميل الطلبات */
        { r: /^تعذر تحميل المنتجات \((.+)\)$/, en: "Couldn't load products ($1)" }, /* تعذر تحميل المنتجات */
        { r: /^(.+) Pi\) وده إجراء نهائي\.$/, en: "$1 Pi) and this is final." }, /* رسالة الإجراء النهائي */
        { r: /^السعر يجب أن يكون أكبر من (.+) Pi \(رسوم المنصة\)$/, en: "Price must be greater than $1 Pi (platform fee)" }, /* رسوم المنصة في رسائل الخطأ */
        { r: /^فشل حفظ المحفظة: (.+)$/, en: "Failed to save wallet: $1" }, /* فشل حفظ المحفظة */
        { r: /^فشل طلب إذن المحفظة: (.+)$/, en: "Failed to request wallet permission: $1" }, /* فشل طلب إذن المحفظة */
    ]
};
