[[CURRENCIES]]
code="ARA"
issuer="GDMV5ABR3CCXT6NN4QBFJOTMUE5STUB7IXT6CAHCSWSFBSDC6UT4RUKR"
name="Arabeka Platform"
desc="العملة الرقمية لمنصة أرابيكا على شبكة Pi Testnet"
image="https://arabeka.vercel.app/logo.png"
