[[CURRENCIES]]
code="ARA"
issuer="GBI34HPZHEHTTL5J5YY3FQSZHGE5M4WDVCKUUP67HSV6ZCTZOXYN2W5K"
name="Arabeka Platform"
desc="العملة الرقمية لمنصة أرابيكا على شبكة Pi Testnet"
image="https://i.ibb.co/wNBgTN37/Screenshot-X.jpg"
